//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoprivrednaGazdinstva.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistracijaPoljoprivrednihGazdinstavaEntities : DbContext
    {
        public RegistracijaPoljoprivrednihGazdinstavaEntities()
            : base("name=RegistracijaPoljoprivrednihGazdinstavaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDokumetacija> tblDokumetacijas { get; set; }
        public virtual DbSet<tblEkspozitura> tblEkspozituras { get; set; }
        public virtual DbSet<tblInstitucija> tblInstitucijas { get; set; }
        public virtual DbSet<tblKorisnik> tblKorisniks { get; set; }
        public virtual DbSet<tblOsiguranje> tblOsiguranjes { get; set; }
        public virtual DbSet<tblPoljoprivrednoGazdinstvo> tblPoljoprivrednoGazdinstvoes { get; set; }
        public virtual DbSet<tblRegistracija> tblRegistracijas { get; set; }
        public virtual DbSet<tblVlasnik> tblVlasniks { get; set; }
        public virtual DbSet<vwDokumentacija> vwDokumentacijas { get; set; }
        public virtual DbSet<vwEkspozitura> vwEkspozituras { get; set; }
        public virtual DbSet<vwInstitucija> vwInstitucijas { get; set; }
        public virtual DbSet<vwKorisnik> vwKorisniks { get; set; }
        public virtual DbSet<vwOsiguranje> vwOsiguranjes { get; set; }
        public virtual DbSet<vwPoljoprivrednoGazdinstvo> vwPoljoprivrednoGazdinstvoes { get; set; }
        public virtual DbSet<vwRegistracija> vwRegistracijas { get; set; }
        public virtual DbSet<vwVlasnik> vwVlasniks { get; set; }
    }
}
