//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoprivrednaGazdinstva.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblDokumetacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDokumetacija()
        {
            this.tblPoljoprivrednoGazdinstvoes = new HashSet<tblPoljoprivrednoGazdinstvo>();
            this.tblVlasniks = new HashSet<tblVlasnik>();
        }
    
        public int DokumetID { get; set; }
        [Display(Name = "Vrsta dokumenta")]
        public string Vrsta { get; set; }
        [Display(Name = "Datum izdavanja")]
        public Nullable<System.DateTime> DatumIzdavanja { get; set; }
        [Display(Name = "Datum isteka")]
        public Nullable<System.DateTime> DatumIsteka { get; set; }
        [Display(Name = "Mesto izdavanja")]
        public string Mesto { get; set; }
        public int Ekspozitura { get; set; }
    
        public virtual tblEkspozitura tblEkspozitura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPoljoprivrednoGazdinstvo> tblPoljoprivrednoGazdinstvoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVlasnik> tblVlasniks { get; set; }
    }
}
