//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoprivrednaGazdinstva.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblOsiguranje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOsiguranje()
        {
            this.tblPoljoprivrednoGazdinstvoes = new HashSet<tblPoljoprivrednoGazdinstvo>();
        }
    
        public int OsiguranjeID { get; set; }
        [Display(Name = "Broj polise")]
        public int BrojPolise { get; set; }
        [Display(Name = "Vrsta osiguranja")]
        public string VrstaOsiguranja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPoljoprivrednoGazdinstvo> tblPoljoprivrednoGazdinstvoes { get; set; }
    }
}
