//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoprivrednaGazdinstva.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblRegistracija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRegistracija()
        {
            this.tblPoljoprivrednoGazdinstvoes = new HashSet<tblPoljoprivrednoGazdinstvo>();
        }
    
        public int RegistracijaID { get; set; }
        [Display(Name = "Datum registracije")]
        public Nullable<System.DateTime> DatumRegistracije { get; set; }
        [Display(Name = "Datum isteka")]
        public Nullable<System.DateTime> DatumIsteka { get; set; }
        [Display(Name = "Cena (u din.)")]
        public string Cena { get; set; }
        [Display(Name = "Registarski broj")]
        public string RegistarskiBroj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPoljoprivrednoGazdinstvo> tblPoljoprivrednoGazdinstvoes { get; set; }
    }
}
