//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoprivrednaGazdinstva.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblVlasnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVlasnik()
        {
            this.tblPoljoprivrednoGazdinstvoes = new HashSet<tblPoljoprivrednoGazdinstvo>();
        }
    
        public int VlasnikID { get; set; }
        [Display(Name = "Adresa gazdinstva")]
        public string Adresa { get; set; }
        public string Grad { get; set; }
        public string Email { get; set; }
        public int Telefon { get; set; }
        public int Dokumentacija { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
    
        public virtual tblDokumetacija tblDokumetacija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPoljoprivrednoGazdinstvo> tblPoljoprivrednoGazdinstvoes { get; set; }
    }
}
