//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoprivrednaGazdinstva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEkspozitura
    {
        public int EkspozituraID { get; set; }
        public int Institucija { get; set; }
        public string Adresa { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Grad { get; set; }
        public string Naziv { get; set; }
    }
}
