//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoprivrednaGazdinstva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOsiguranje
    {
        public int OsiguranjeID { get; set; }
        public int BrojPolise { get; set; }
        public string VrstaOsiguranja { get; set; }
    }
}
