//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoprivrednaGazdinstva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRegistracija
    {
        public int RegistracijaID { get; set; }
        public Nullable<System.DateTime> DatumRegistracije { get; set; }
        public Nullable<System.DateTime> DatumIsteka { get; set; }
        public string Cena { get; set; }
        public string RegistarskiBroj { get; set; }
    }
}
